export const highValueList = [
    {
        "Id": 1,
        "name": "Alpha Corp.",
        "opportunity": "Development of Unit Gen..",
        "dealSize": "$124,323",
        "avatId1": "https://material-ui.com/static/images/avatar/1.jpg",
        "avatId2": "https://material-ui.com/static/images/avatar/2.jpg",
        "avatId3": "https://material-ui.com/static/images/avatar/3.jpg",
        "pending": "03",
    },
    {
        "Id": 2,
        "name": "Zeta Century",
        "opportunity": "Multiple Solutions for Com..",
        "dealSize": "$314,323",
        "avatId1": "https://material-ui.com/static/images/avatar/1.jpg",
        "avatId2": "",
        "avatId3": "",
        "pending": "01",
    },
    {
        "Id": 3,
        "name": "Bezel Soft Inc",
        "opportunity": "Mastermind DevOps: Make..",
        "dealSize": "$344,323",
        "avatId1": "https://material-ui.com/static/images/avatar/1.jpg",
        "avatId2": "https://material-ui.com/static/images/avatar/2.jpg",
        "avatId3": "",
        "pending": "03",
    },
    {
        "Id": 4,
        "name": "GrisWalleque",
        "opportunity": "Data Driven Complex for A3",
        "dealSize": "$314,323",
        "avatId1": "https://material-ui.com/static/images/avatar/1.jpg",
        "avatId2": "",
        "avatId3": "",
        "pending": "01",
    },
    {
        "Id": 5,
        "name": "CrisperTech",
        "opportunity": "Magic Solutions web/app",
        "dealSize": "$44,331",
        "avatId1": "https://material-ui.com/static/images/avatar/1.jpg",
        "avatId2": "",
        "avatId3": "",
        "pending": "03",
    },
]